footprint: [[-0.11, -0.10], [-0.11, 0.10], [0.11, 0.10], [0.11, -0.10]] # change scale(0.5 to 0.11)
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true, obstacle_range: 5.5}

inflation:
    inflation_radius: 0.8 # meter
    cost_scaling_factor : 10.0